### ISSUE TITLE
RemovedInDjango19Warning deprecated warnings

### ISSUE THREAD

**Issue by epicserve** [sehmaschine/django-grappelli#598]
I using the latest version of grappelli (2.6.4) to test with Django 1.8.

When I run my tests I'm getting the following:

```bash
/Users/xxxxxx/.virtualenvs/xxxxx/lib/python2.7/site-packages/django/contrib/contenttypes/models.py:159: RemovedInDjango19Warning: Model class django.contrib.contenttypes.models.ContentType doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class ContentType(models.Model):
```

To debug I ran ``python -W 'error:Model class' manage.py test --failfast`` which gives me the following traceback:

```bash
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/xxxxxx/.virtualenvs/xxxxx/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/Users/xxxxxx/.virtualenvs/xxxxx/lib/python2.7/site-packages/django/core/management/__init__.py", line 312, in execute
    django.setup()
  File "/Users/xxxxxx/.virtualenvs/xxxxx/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/xxxxxx/.virtualenvs/xxxxx/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/Users/xxxxxx/.virtualenvs/xxxxx/lib/python2.7/site-packages/django/apps/config.py", line 86, in create
    module = import_module(entry)
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/xxxxxx/.virtualenvs/xxxxx/lib/python2.7/site-packages/grappelli/dashboard/__init__.py", line 1, in <module>
    from grappelli.dashboard.dashboards import *
  File "/Users/xxxxxx/.virtualenvs/xxxxx/lib/python2.7/site-packages/grappelli/dashboard/dashboards.py", line 13, in <module>
    from grappelli.dashboard import modules
  File "/Users/xxxxxx/.virtualenvs/xxxxx/lib/python2.7/site-packages/grappelli/dashboard/modules.py", line 9, in <module>
    from django.contrib.contenttypes.models import ContentType
  File "/Users/xxxxxx/.virtualenvs/xxxxx/lib/python2.7/site-packages/django/contrib/contenttypes/models.py", line 159, in <module>
    class ContentType(models.Model):
  File "/Users/xxxxxx/.virtualenvs/xxxxx/lib/python2.7/site-packages/django/db/models/base.py", line 116, in __new__
    warnings.warn(msg, RemovedInDjango19Warning, stacklevel=2)
django.utils.deprecation.RemovedInDjango19Warning: Model class django.contrib.contenttypes.models.ContentType doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
```

I also go this warning:

```bash
/Users/xxxxxx/.virtualenvs/xxxxx/lib/python2.7/site-packages/django/contrib/admin/util.py:7: RemovedInDjango19Warning: The django.contrib.admin.util module has been renamed. Use django.contrib.admin.utils instead.
  "Use django.contrib.admin.utils instead.", RemovedInDjango19Warning)
```

To debug I ran ``python -W 'error:The django.contrib.admin.util' manage.py test --failfast`` which gives me the following traceback:

```bash
Traceback (most recent call last):
  File "/Users/xxxxxx/Sites/oeie/xxxxx-django/apps/accounts/tests/test_ajax.py", line 35, in test_get_user_by_id
    url = reverse('accounts:get_user_by_id', args=[self.normal_user.pk])
  File "/Users/xxxxxx/.virtualenvs/xxxxx/lib/python2.7/site-packages/django/core/urlresolvers.py", line 550, in reverse
    app_list = resolver.app_dict[ns]
  File "/Users/xxxxxx/.virtualenvs/xxxxx/lib/python2.7/site-packages/django/core/urlresolvers.py", line 352, in app_dict
    self._populate()
  File "/Users/xxxxxx/.virtualenvs/xxxxx/lib/python2.7/site-packages/django/core/urlresolvers.py", line 285, in _populate
    for pattern in reversed(self.url_patterns):
  File "/Users/xxxxxx/.virtualenvs/xxxxx/lib/python2.7/site-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/xxxxxx/.virtualenvs/xxxxx/lib/python2.7/site-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/xxxxxx/Sites/oeie/xxxxx-django/config/urls.py", line 30, in <module>
    url(r'^grappelli/', include('grappelli.urls')),
  File "/Users/xxxxxx/.virtualenvs/xxxxx/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/xxxxxx/.virtualenvs/xxxxx/lib/python2.7/site-packages/grappelli/urls.py", line 7, in <module>
    from .views.related import RelatedLookup, M2MLookup, AutocompleteLookup
  File "/Users/xxxxxx/.virtualenvs/xxxxx/lib/python2.7/site-packages/grappelli/views/related.py", line 17, in <module>
    from django.contrib.admin.util import prepare_lookup_value
  File "/Users/xxxxxx/.virtualenvs/xxxxx/lib/python2.7/site-packages/django/contrib/admin/util.py", line 7, in <module>
    "Use django.contrib.admin.utils instead.", RemovedInDjango19Warning)
RemovedInDjango19Warning: The django.contrib.admin.util module has been renamed. Use django.contrib.admin.utils instead.
```

**Comment by epicserve** [comment]
@sehmaschine I've tested out 'dev/2.7.x', it seems to get rid of most of the RemovedInDjango19Warning(s). However I was still getting the "Model class django.contrib.contenttypes.models.ContentType ..." warning and discovered that moving ``'grappelli.dashboard'`` in my installed apps from the beginning to the end fixed that warning.

I also noticed that in grappelli's templates the tags url, firstof and cycle are loaded from the future, which generates RemovedInDjango19Warning(s). I'm not sure how you want to handle that because if removed, it would break things for older versions of Django.

**Comment by sehmaschine** [comment]
dev/2.7.x is only working with Django 1.8 (it doesn't have to be backwards compatible because there are other versions of grappelli which work with older versions of django).

**Comment by epicserve** [comment]
@sehmaschine Want me to remove them and submit a PR?

**Comment by sehmaschine** [comment]
that's much appreciated!

**Comment by sehmaschine** [comment]
Should work now. I'll add a note about adding ``grappelli.dashboard`` after ``django.contrib.contenttypes`` to INSTALLED_APPS.

**Comment by sehmaschine** [comment]
Closing this for now since all warnings should be gone (with stable/2.7.x). Please reopen if the issue still exists.

**Comment by jlicht** [comment]
This issue still exists with: 
Django: 1.8.2
Python 3.4.3
django-grappelli 2.7.1

I was able to resolve it by moving ```grappelli.dashboard``` after ```django.contrib.contenttypes``` as described above

**Comment by Aisuko** [comment]
The same issue:
Django 1.8
python 2.7.13
